<?php
/**
 * Generated by scripts/sync-wordpress.mjs. Do not edit by hand.
 *
 * The body of a <svg viewBox="0 0 24 24"> for each preference, taken
 * straight from the component so the two cannot disagree.
 *
 * @package A11y_Prefs
 */

defined( 'ABSPATH' ) || exit;

return array(
	'fontSize' => '<path d="M3 20 9 4h2l6 16M5.5 14h9M16 20l3-8h1l3 8M17.2 17.5h4.6"/>',
	'textSpacing' => '<path d="M3 5h18M3 19h18M7 9h10M7 12h10M7 15h10"/>',
	'contrast' => '<circle cx="12" cy="12" r="9"/><path d="M12 3v18a9 9 0 0 0 0-18Z"/>',
	'dyslexia' => '<path d="M4 19V7a3 3 0 0 1 6 0v12M4 13h6M14 5h6l-6 14h6"/>',
	'links' => '<path d="M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1 1M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1-1"/>',
	'newTab' => '<path d="M14 4h6v6M20 4l-8 8M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/>',
	'headings' => '<path d="M5 5v14M13 5v14M5 12h8M17 19v-8l4 8v-8"/>',
	'focusOutline' => '<circle cx="12" cy="12" r="3"/><path d="M4 8V5a1 1 0 0 1 1-1h3M20 8V5a1 1 0 0 0-1-1h-3M4 16v3a1 1 0 0 0 1 1h3M20 16v3a1 1 0 0 1-1 1h-3"/>',
	'fields' => '<path d="M3 8h18v8H3zM7 11v2M10 11h7"/>',
	'stopAnimations' => '<circle cx="12" cy="12" r="9"/><path d="M9 9h2v6H9zM13 9h2v6h-2z"/>',
	'noSticky' => '<path d="M9 4h6l-1 5 3 3v2h-4M12 14v6M3 3l18 18"/>',
	'readingHelp' => '<path d="M3 6h18M3 12h18M3 18h18M7 12l-2 2 2 2"/>',
	'bigCursor' => '<path d="M5 3l14 9-6 1.5L10.5 20z"/>',
	'hideImages' => '<path d="M3 5h18v14H3zM3 16l5-5 4 4 3-3 6 6"/><circle cx="8.5" cy="9" r="1.5"/><path d="M3 3l18 18"/>',
	'alignStart' => '<path d="M3 5h18M3 9h12M3 13h18M3 17h12"/>',
	'selection' => '<path d="M5 4h14v16H5z"/><rect x="8" y="9" width="8" height="3"/>',
);
